defaults:
  - anchor_ode_v2_v3_camus_skip_only_tta
  - _self_

exp_id: "anchor_ode_v2_v3_camus_skip_only_capacity"


model:
  anchor_ode:
    hidden_dim: 160
    guidance_proj_hidden_dim: 16
    lambda_guided_seg: 0.25
    lambda_affine_reg: 0.01
