defaults:
  - anchor_ode_v2_v4_camus_skip_long_repro
  - _self_

exp_id: "anchor_ode_v2_v4_camus_early_sched"


main_training:
  num_iterations: 3000
  lr_schedule: step
  lr_schedule_steps: [1600, 2400]
  lr_schedule_gamma: 0.1
