defaults:
  - cardia_cardiacuda_r2g
  - _self_

exp_id: "cardia_n2_cardiacuda_r2g"
model_name: "CARDIA_N2"

model:
  cardia:
    base_dim: 120
    backbone:
      name: "official"
      official:
        mlp_expansion: 2.0
        latent_blocks: 2
        decoder_mlp_blocks: 1

mlflow:
  tags:
    method: "CARDIA_N2"
    version: "n2_official_mlp2"
    backbone: "unext_official"
