defaults:
  - config_unext_dynakey_spatial
  - _self_

exp_id: "unext_dynakey_spatial_no_phase_v2_no_leak"
model_name: "UNeXtDynaKeySpatialNoPhase"

model:
  unext_dynakey:
    use_phase_retrieval: false
