defaults:
  - config_unext_dynakey
  - _self_

exp_id: "unext_only_base64_v2_no_leak"
model_name: "UNeXtOnly"


model:
  memory_core:
    type: "none"
  temporal_memory:
    type: "none"
  unext_dynakey:
    base_dim: 64
    use_dynakey: false
    use_temporal_refine: false
    use_mask_memory: false
    use_memory_readout: false

main_training:
  point_supervision: false
