defaults:
  - config_delay_ode
  - _self_

exp_id: "delay_ode_no_smooth"
model:
  delay_ode:
    delay_ode_lambda_gate_smooth: 0.0
    delay_ode_lambda_latent_smooth: 0.0
    delay_ode_lambda_state_smooth: 0.0
