defaults:
  - config_unext_dynakey
  - _self_

exp_id: "unext_temporal_refine_v2_no_leak"
model_name: "UNeXtTemporalRefine"


model:
  memory_core:
    type: "none"
  temporal_memory:
    type: "none"
  unext_dynakey:
    use_dynakey: false
    use_temporal_refine: true
    use_mask_memory: false
    use_memory_readout: false
