defaults:
  - config_unext_dynakey_spatial
  - _self_

exp_id: "unext_dynakey_spatial_q_training_v2_no_leak"
model_name: "UNeXtDynaKeySpatialQTraining"

model:
  unext_dynakey:
    q_policy_mode: "training"
    enable_q_loss: true
    lambda_q_ce: 1.0
