defaults:
  - config_unext_dynakey_spatial
  - _self_

exp_id: "unext_dynakey_spatial_memory_primary_v2_no_leak"
model_name: "UNeXtDynaKeySpatialMemoryPrimary"


model:
  unext_dynakey:
    memory_fusion_level: "decoder"
    prediction_mode: "memory_primary"
    base_logits_weight: 0.0
    detach_base_logits: true
    base_prob_dropout: 0.25
    decoder_feature_dropout: 0.10
    use_temporal_refine: false
    memory_only_head_enabled: true
    lambda_memory_only: 0.2
