defaults:
  - debel_camus_fair_dense10
  - _self_

exp_id: "debel_camus_fair_dense10_maxdisp010"

model:
  debel:
    max_disp: 0.10

mlflow:
  run_name: "debel_camus_fair_dense10_maxdisp010"
  tags:
    max_disp: "0.10"
