defaults:
  - delay_ode_camus
  - _self_

exp_id: "delay_ode_v2_camus"

wandb:
  group: "canonical_delay_ode_v2"
  tags: ["canonical", "delay_ode", "delay_ode_v2", "camus", "no_leak", "strong_init"]

