defaults:
  - delay_ode_v2_echo
  - _self_

exp_id: "delay_ode_v2_no_latent_decode"

model:
  delay_ode:
    delay_ode_use_decodable_latent_regularizer: false
    delay_ode_lambda_latent_decode_low: 0.0
    delay_ode_lambda_latent_decode_mid: 0.0
    delay_ode_lambda_latent_decode_high: 0.0
