defaults:
  - gdkvm_cardiacuda_sparse_sitegen
  - _self_

exp_id: "gdkvm_cardiacuda_g2r"

data_path: "${processed_root}/cardiacuda_a4c_lv_g2r_png128_10f"

data:
  protocol_name: "cardiacuda_a4c_lv_sparse_g2r"

evaluation:
  eval_protocol: "cardiacuda_g2r_noinit"

mlflow:
  experiment_name: "cardiacuda_cross_domain_g2r"
  tags:
    protocol: "G_to_R"
    source_domain: "G"
    target_domain: "R"
