defaults:
  - geomaskformer_camus
  - _self_

exp_id: "geomaskformer_stage1_camus"

model:
  geomaskformer:
    training_stage: "stage1"
    condition_dropout: 0.0
    mask_token_dropout: 0.0
    loss:
      temporal: 0.0

main_training:
  seq_length: 3
  num_iterations: 2500

mlflow:
  tags:
    protocol: "stage1_single_frame_proposal"
