defaults:
  - cardia_cardiacuda_g2r
  - /_base_/models/rebel@_global_
  - _self_

exp_id: "rebel_cardiacuda_g2r"
model_name: "ReBel"

model:
  name: "rebel"

loss:
  name: "rebel"

main_training:
  cardia_lr_ratio: null
  rebel_lr_ratio: 1.0

mlflow:
  experiment_name: "rebel"
  run_name: "rebel_cardiacuda_g2r"
  tags:
    method: "ReBel"
    full_name: "Resampled Belief Network for Decoupled Video Segmentation"
    dataset: "cardiacuda"
    protocol: "g2r"
    backbone: "unext_official"
