defaults:
  - cardia_cardiacuda_sparse_sitegen
  - /_base_/models/rebel@_global_
  - _self_

exp_id: "rebel_cardiacuda_sparse_sitegen"
model_name: "ReBel"

model:
  name: "rebel"

loss:
  name: "rebel"

main_training:
  cardia_lr_ratio: null
  rebel_lr_ratio: 1.0

mlflow:
  experiment_name: "rebel"
  run_name: "rebel_cardiacuda_sparse_sitegen"
  tags:
    method: "ReBel"
    full_name: "Resampled Belief Network for Decoupled Video Segmentation"
    dataset: "cardiacuda"
    protocol: "sparse_sitegen"
    backbone: "unext_official"
