defaults:
  - unext_faf_echo_online
  - _self_

exp_id: "unext_faf_echo_ablate_single_anchor"
ablation_type: "single_anchor"

model:
  unext_faf:
    num_anchors: 1
    lambda_faf_sparse: 0.0
    lambda_faf_diversity: 0.0
