defaults:
  - gdkvm_echo
  - _self_

exp_id: "gdkvm_echonet_pediatric_a4c"

data_path: "${processed_root}/echonet_pediatric_a4c_png128_10f"

data:
  protocol_name: "echonet_pediatric_a4c_endpoint"

mlflow:
  experiment_name: "gdkvm_echonet_pediatric_a4c"
  tags:
    method: "GDKVM"
    dataset: "echonet_pediatric"
    view: "A4C"
